name: agent3-bm25
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Law-Tools (this repo)
        uses: actions/checkout@v4

      - name: Checkout target repo (Law-Texts-ui)
        uses: actions/checkout@v4
        with:
          repository: Info1691/Law-Texts-ui
          path: target
          token: ${{ secrets.TEXTS_RW_TOKEN }}

      - name: Set git identity for commits
        run: |
          git config --global user.name  "Agent3"
          git config --global user.email "agent3@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (lunr only)
        run: npm i lunr@2

      - name: Build BM25 index
        env:
          OUT: out
          BASE: https://texts.wwwbcb.org/
          # Prefer URLs; you can swap to PATHs if you want to read from the checked-out repo:
          CATALOG_TEXTBOOKS_URL: https://texts.wwwbcb.org/texts/catalog.json
          CATALOG_LAWS_URL:      https://texts.wwwbcb.org/laws.json
          CATALOG_RULES_URL:     https://texts.wwwbcb.org/rules.json
        run: node scripts/agent3_build.mjs

      - name: Copy files into Law-Texts-ui/agent3-bm25
        run: |
          mkdir -p target/agent3-bm25
          cp -f out/agent3.json out/agent3.meta.json out/lunr-index.json out/chunks.jsonl target/agent3-bm25/

      - name: Commit & push to Law-Texts-ui
        working-directory: target
        run: |
          git add agent3-bm25
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "agent3-bm25: refresh index bundle"
            git push
          fi
