name: agent3-bm25
on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Law-Tools (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout target repo (Law-Texts-ui)
        uses: actions/checkout@v4
        with:
          repository: Info1691/Law-Texts-ui
          ref: main
          path: target
          fetch-depth: 1
          persist-credentials: true
          token: ${{ secrets.TEXTS_RW_TOKEN }}

      - name: Set git identity for commits
        run: |
          git config --global user.name  "Agent3"
          git config --global user.email "agent3@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # install 'lunr' (and any other deps in package.json)
      - name: Install deps (lunr only)
        run: |
          set -e
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      # <<< KEY FIX: point TARGET at the checked-out Law-Texts-ui >>>
      - name: Build BM25 index
        env:
          TARGET: ${{ github.workspace }}/target
          OUT:    ${{ github.workspace }}/out
          NODE_OPTIONS: --max_old_space_size=2048
        run: |
          set -euxo pipefail
          # sanity check: catalog must exist in the target repo
          test -f "$TARGET/texts/catalog.json"
          node scripts/agent3_build.mjs
          ls -l "$OUT"
          test -f "$OUT/agent3.json"
          test -f "$OUT/agent3.meta.json"

      - name: Copy files into Law-Texts-ui/agent3-bm25
        run: |
          set -e
          mkdir -p target/agent3-bm25
          cp -f out/* target/agent3-bm25/

      - name: Commit & push to Law-Texts-ui
        working-directory: target
        run: |
          if [ -n "$(git status --porcelain agent3-bm25)" ]; then
            git add agent3-bm25
            git commit -m "agent3: refresh BM25 index"
            git push origin main
          else
            echo "No changes to commit."
          fi
