name: agent3-bm25

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Law-Tools (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout target repo (Law-Texts-ui)
        uses: actions/checkout@v4
        with:
          repository: Info1691/Law-Texts-ui
          ref: main
          path: target
          fetch-depth: 1
          persist-credentials: true
          token: ${{ secrets.TEXTS_RW_TOKEN }}

      - name: Set git identity for commits
        run: |
          git config --global user.name  "Agent3"
          git config --global user.email "agent3@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # <-- THIS is the fix: use npm ci only when a lockfile exists,
      # otherwise fall back to npm install so lunr is available.
      - name: Install deps (lunr only)
        run: |
          set -e
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Build BM25 index
        env:
          NODE_OPTIONS: --max_old_space_size=2048
        run: |
          set -e
          node scripts/agent3_build.mjs --target ./target --out ./out
          echo "Built files:"
          ls -l ./out
          test -f ./out/agent3.json
          test -f ./out/agent3.meta.json

      - name: Copy files into Law-Texts-ui/agent3-bm25
        run: |
          mkdir -p target/agent3-bm25
          cp -f out/* target/agent3-bm25/

      - name: Commit & push to Law-Texts-ui
        working-directory: target
        run: |
          if [ -n "$(git status --porcelain agent3-bm25)" ]; then
            git add agent3-bm25
            git commit -m "agent3: refresh BM25 index"
            git push origin main
          else
            echo "No changes to commit."
          fi
