name: agent3-bm25

on:
  workflow_dispatch: {}

permissions:
  contents: write

env:
  # Where the four output files will be copied in Law-Texts-ui
  DEST_DIR: agent3-bm25
  # The three catalogs the index must read
  CATALOGS: |
    https://texts.wwwbcb.org/texts/catalog.json
    https://texts.wwwbcb.org/laws.json
    https://texts.wwwbcb.org/rules.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Law-Tools (this repo)
        uses: actions/checkout@v4

      - name: Checkout target repo (Law-Texts-ui)
        uses: actions/checkout@v4
        with:
          repository: Info1691/Law-Texts-ui
          token: ${{ secrets.TEXTS_RW_TOKEN }}
          path: target

      - name: Set git identity for commits
        run: |
          git config --global user.name "Agent3"
          git config --global user.email "agent3@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (lunr only)
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install lunr@2.3.9

      - name: Build BM25 index
        env:
          CATALOGS: ${{ env.CATALOGS }}
        run: |
          set -euxo pipefail
          mkdir -p out
          node scripts/agent3_build.mjs --out ./out --catalogs "$CATALOGS"

          # sanity checks
          test -f ./out/agent3.json
          test -f ./out/agent3.meta.json
          test -f ./out/lunr-index.json
          test -f ./out/chunks.jsonl

          echo "Built index:"
          jq '. | {catalogItems, docs, chunkCount}' ./out/agent3.meta.json

      - name: Copy files into Law-Texts-ui/${{ env.DEST_DIR }}
        run: |
          set -eux
          mkdir -p target/${{ env.DEST_DIR }}
          cp -f out/agent3.json out/agent3.meta.json out/lunr-index.json out/chunks.jsonl target/${{ env.DEST_DIR }}/

      - name: Commit & push to Law-Texts-ui
        working-directory: target
        run: |
          set -eux
          git add ${{ env.DEST_DIR }}/agent3.json ${{ env.DEST_DIR }}/agent3.meta.json ${{ env.DEST_DIR }}/lunr-index.json ${{ env.DEST_DIR }}/chunks.jsonl
          git commit -m "agent3: refresh BM25 index" || echo "Nothing to commit"
          git push
