name: agent3-bm25
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Law-Tools (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (lunr only)
        run: npm i --no-audit --no-fund lunr@2.3.9

      - name: Checkout target repo (Law-Texts-ui)
        uses: actions/checkout@v4
        with:
          repository: Info1691/Law-Texts-ui
          path: target
          token: ${{ secrets.TEXTS_RW_TOKEN }}
          fetch-depth: 0

      - name: Build BM25 index (write into Law-Texts-ui)
        env:
          NODE_OPTIONS: --max-old-space-size=6144
        run: |
          mkdir -p target/data/agent3
          node scripts/agent3_build.mjs --out target/data/agent3
          echo "---- OUTPUTS IN Law-Texts-ui ----"
          ls -lh target/data/agent3 || true

      - name: Verify outputs exist
        run: |
          test -s target/data/agent3/lunr-index.json
          test -s target/data/agent3/chunks.jsonl
          echo "Size (lunr-index.json): $(wc -c < target/data/agent3/lunr-index.json) bytes"
          echo "Size (chunks.jsonl)    : $(wc -c < target/data/agent3/chunks.jsonl) bytes"

      - name: Commit & push to Law-Texts-ui
        run: |
          cd target
          git config user.name  "agent3"
          git config user.email "agent3@users.noreply.github.com"
          git add data/agent3/lunr-index.json data/agent3/chunks.jsonl || true
          if git diff --cached --quiet; then
            echo "No changes to commit for Law-Texts-ui."
          else
            git commit -m "agent3: refresh BM25 index"
            git pull --rebase || true
            git push
          fi

      # Fallback publish into Law-Tools site too
      - name: Copy fallback into Law-Tools (this repo)
        run: |
          mkdir -p data/agent3
          cp target/data/agent3/lunr-index.json data/agent3/
          cp target/data/agent3/chunks.jsonl    data/agent3/
          echo "---- OUTPUTS IN Law-Tools ----"
          ls -lh data/agent3 || true
          git add data/agent3/lunr-index.json data/agent3/chunks.jsonl || true

      - name: Configure Git (Law-Tools) & commit fallback
        run: |
          git config user.name  "agent3"
          git config user.email "agent3@users.noreply.github.com"
          if git diff --cached --quiet; then
            echo "No fallback changes to commit."
          else
            git commit -m "agent3: publish fallback index under tools"
            git pull --rebase || true
            git push
          fi
