name: agent3-bm25

on:
  workflow_dispatch: {}

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.TEXTS_RW_TOKEN }}
  TARGET_REPO: Info1691/Law-Texts-ui
  TARGET_PATH: target
  OUT_PATH: out

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Law-Tools (this repo)
        uses: actions/checkout@v4

      - name: Checkout target repo (Law-Texts-ui)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          path: ${{ env.TARGET_PATH }}
          token: ${{ env.GH_TOKEN }}

      - name: Set git identity for commits
        run: |
          git config --global user.name  "Agent3"
          git config --global user.email "agent3@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (lunr only)
        run: npm i lunr

      - name: Build BM25 index
        run: |
          node scripts/agent3_build.mjs --target ./${{ env.TARGET_PATH }} --out ./${{ env.OUT_PATH }}
          ls -lah ./${{ env.OUT_PATH }}

      - name: Copy files into Law-Texts-ui/agent3-bm25
        run: |
          mkdir -p ${{ env.TARGET_PATH }}/agent3-bm25
          cp -f ${{ env.OUT_PATH }}/lunr-index.json  ${{ env.TARGET_PATH }}/agent3-bm25/
          cp -f ${{ env.OUT_PATH }}/chunks.jsonl     ${{ env.TARGET_PATH }}/agent3-bm25/

      - name: Commit & push to Law-Texts-ui
        working-directory: ${{ env.TARGET_PATH }}
        run: |
          git add agent3-bm25/lunr-index.json agent3-bm25/chunks.jsonl
          git commit -m "agent3: refresh BM25 index"
          git push
