name: Agent3 — UI + Branding + pull index from texts (Rule 12)

on:
  workflow_dispatch:
  push:
    paths:
      - 'agent3.html'
      - 'txt-viewer.html'
      - 'brand.css'
      - 'agent3.css'
      - 'logo.png'
      - 'scripts/**'
      - '.github/workflows/agent3-deploy.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify UI files
        run: |
          test -f agent3.html || (echo "ERROR: agent3.html missing" && exit 1)
          test -f txt-viewer.html || (echo "ERROR: txt-viewer.html missing" && exit 1)
          test -f brand.css || (echo "ERROR: brand.css missing" && exit 1)
          test -f agent3.css || (echo "ERROR: agent3.css missing" && exit 1)

      - name: Assemble site
        run: |
          mkdir -p dist dist/agent3 dist/scripts
          cp -f agent3.html     dist/agent3.html
          cp -f txt-viewer.html dist/txt-viewer.html
          cp -f brand.css       dist/brand.css
          cp -f agent3.css      dist/agent3.css
          if [ -f logo.png ]; then cp -f logo.png dist/logo.png; fi
          if [ -f scripts/citation-spotter.js ]; then cp -f scripts/citation-spotter.js dist/scripts/citation-spotter.js; fi

      - name: Pull index from texts.wwwbcb.org
        run: |
          set -e
          base="https://texts.wwwbcb.org/agent3-bm25"
          mkdir -p dist/agent3
          for f in agent3.meta.json lunr-index.json chunks.jsonl; do
            echo "Fetching $base/$f"
            curl -fsSL "$base/$f" -o "dist/agent3/$f"
          done
          echo "Fetched index into dist/agent3"

      - name: Add CNAME
        run: echo "tools.wwwbcb.org" > dist/CNAME

      - name: List dist
        run: find dist -maxdepth 3 -type f -print

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
