name: catalog-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * *" # daily 03:17 UTC (optional)

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Law-Tools (this repo)
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Sync catalogs (update url_txt automatically)
        env:
          GH_TOKEN: ${{ secrets.LAW_SYNC_TOKEN }}
        run: node scripts/catalog-sync.mjs
