name: catalog-sync

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Law-Tools (this repo)
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Use install (not ci) — no lockfile needed
      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Sync catalogs (update url_txt automatically)
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}   # Personal Access Token with repo scope
          TEXTS_OWNER: Info1691
          TEXTS_REPO: Law-Texts-ui
          TEXTS_BRANCH: main
          TEXTS_BASE: https://texts.wwwbcb.org
        run: node scripts/catalog-sync.mjs
