name: Relocate TXT

on:
  workflow_dispatch:
    inputs:
      plan:
        description: "JSON array of move specs (see scripts/plan.json format)"
        required: false
        type: string
        default: |
          [
            {
              "src_owner": "Info1691",
              "src_repo": "rules-ui",
              "src_path": "data/rules/uk/icaew-code.txt",
              "dst_path": "data/rules/uk/icaew-code.txt",
              "message": "Relocate ICAEW code to canonical rules folder"
            }
          ]

jobs:
  relocate:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed for create/update/delete via API
    steps:
      - name: Checkout Law-Tools (this repo)
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Run relocator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_OWNER: "Info1691"
          TARGET_REPO: "Law-Texts-ui"
          TARGET_BRANCH: "main"
          PLAN: ${{ inputs.plan }}
        run: npm run relocate
