name: relocate

on:
  workflow_dispatch:
    inputs:
      plan:
        description: 'JSON array of move instructions'
        required: false
        default: ''
      plan_path:
        description: 'Optional path to a JSON plan file in repo (e.g., scripts/plan.json)'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Law-Tools (this repo)
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Run relocator
        env:
          GH_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          PLAN: ${{ github.event.inputs.plan }}
          PLAN_PATH: ${{ github.event.inputs.plan_path }}
        run: node scripts/relocate.mjs
