name: relocate

on:
  workflow_dispatch:
    inputs:
      plan:
        description: "Optional JSON array of moves; if empty, auto-scan and relocate"
        required: false
        default: ""
      repos:
        description: "Comma-separated owner/repo to scan (defaults cover your setup)"
        required: false
        default: "Info1691/Law-Texts-ui,Info1691/laws-ui,Info1691/rules-ui,Info1691/lex-ingest-local"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Law-Tools (this repo)
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Run relocator
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_PLAN: ${{ github.event.inputs.plan }}
          INPUT_REPOS: ${{ github.event.inputs.repos }}
        run: node scripts/relocate.mjs
